### ISSUE TITLE
JUnitParser does not detect failures in xml generated by Ant's Junit task

### ISSUE THREAD

**Issue by schlm3** [tomasbjerre/violations-lib#85] opened 2020-05-12 14:19 UTC
We use Ant as our build tool and orchestrate the overall build-pipeline using scripted pipeline in Jenkins. For the Tests, we call the ant-Junit target out of the Jenkinsfile. The result is a JUnit results file as XML. Unitl today, we always used the Jenkins integrated "junit" pipeline step to parse the build result. Today, I have integrated spotbugs tests using the warings-ng plugin and then tried to use that one also for the junit tests. Unfortunately, the JUnit-Parser of warnings-ng fails to parse the junit-xml result file correctly. While "JUnit" reports 2 failures, warnings-ng reports "success"!
The Jenkinsfile code:
`recordIssues failOnError: true, sourceDirectory: 'src', qualityGates: [[threshold: 1, type: 'TOTAL', unstable: false]], tools: [junitParser(pattern: 'tests/reports/TESTS-TestSuites.xml')]`

The JUnit result file:
[TESTS-TestSuites.zip](https://github.com/tomasbjerre/violations-lib/files/4616157/TESTS-TestSuites.zip)

**Comment by tomasbjerre** [comment] 2020-05-12 15:02
Thanks for reporting. Found it and released in 1.114

**Closed by tomasbjerre** 2020-05-12 15:02 UTC

**Comment by schlm3** [comment] 2020-05-13 07:55
When / how will this fix come to jenkins?

**Comment by tomasbjerre** [comment] 2020-05-13 08:29
You can open a bug on warnings plugin. @uhafner is usually very quick!

**Comment by schlm3** [comment] 2020-05-13 09:41
Unfortunately no. There is no such option on the warnings-ng project. Only pull requests, and I can't provide one since I have no idea how that project works.
Fortunately, I found https://github.com/jenkinsci/analysis-model/pull/364 
Thanks to "dependabot", there is no need for a seperate bug report or pull request.

**Comment by schlm3** [comment] 2020-06-03 11:16
@uhafner : Could you please consider making a new release of warnings-ng-plugin such that this fix is being picked up?

**Comment by uhafner** [comment] 2020-06-03 13:22
See https://plugins.jenkins.io/analysis-model-api/

**Comment by uhafner** [comment] 2020-06-04 07:35
There is no need to release the warnings plugin, because the dependency that you are referring to is just a compile dependency. During runtime it will be replaced by the latest plugin that is deployed in your Jenkins instance. So if you use Analysis Model API 8.1.3 in your Jenkins then the violations lib is in the correct version. 

So I think the problem is related to something different. Maybe there is something wrong at a different place? You can create an issue in Jenkins JIRA with the file above files, then we can see where the problem is.

**Comment by schlm3** [comment] 2020-06-07 12:43
I checked this again, and yes, it is indeed working now. It might be, that I checked the wrong build (the one before the jenkins update). Sorry for that and thanks for your support.
